### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by quyanqiu** [sturkmen72/C4-Real-time-pedestrian-detection#1]
excuse me,have you really test your code? why when  I test my video with some pedestrain but none of them are maeked with green rectangle?(Ps: I used the same video as yours,just the one that opencv released)
![qq 20160831101849](https://cloud.githubusercontent.com/assets/11349003/18113690/55f9570c-6f64-11e6-9a95-5105924bdc79.png)

**Comment by sturkmen72** [comment]
you can try the original code can be found at https://sites.google.com/site/wujx2001/home/c4
are you using 32 bit Windows ? i did not test on 32 bit  Windows
