### ISSUE TITLE
contour extraction

### ISSUE THREAD

**Issue by gitgoready** [sturkmen72/C4-Real-time-pedestrian-detection#3]
Good work，I have a question, can we extract only human contour part from the video,remove background using this C4 method? and how? thank you very much !

**Comment by sturkmen72** [comment]
i think it is hard to achieve your purpose only using this code.maybe [this example](https://github.com/opencv/opencv/blob/master/samples/tapi/bgfg_segm.cpp) will be a starting point  if you have a static background and moving people.

![foreground image](https://user-images.githubusercontent.com/12151541/31783999-e2d1491a-b508-11e7-9a05-76061e01a1c6.png)

**Comment by gitgoready** [comment]
Thanks a lot!
