### ISSUE TITLE
Hello,I meet a problem in running the program.

### ISSUE THREAD

**Issue by ziyanwang** [sturkmen72/C4-Real-time-pedestrian-detection#5]
hello, I compile and run this code but I don't know how to use it in the video people detection ,I would be grateful if you could give me some advice.

**Comment by sturkmen72** [comment]
see https://github.com/sturkmen72/C4-Real-time-pedestrian-detection/blob/master/c4-pedestrian-detector.cpp#L1075-L1083

**Comment by ziyanwang** [comment]
Thank you so much ,but in the next two line,
if (argc < 2)
	return 0;
If I run it ,it will return 0,and don't open the video.
And if I delete them and run, It will have a warning , and still can't open the video. So I want to get some advice.   ^O^  Thank you!
![image](https://user-images.githubusercontent.com/31835386/37705838-45f67fe0-2d38-11e8-91f7-e47abaf92529.png)

**Comment by sturkmen72** [comment]
call it with path of video file

**Comment by ziyanwang** [comment]
Thanks a lot , I hear your advice and now a window is popped out, I'm very happy. But now the problem is that the window don't show any thing, couldn't show the video, only pop a window and the window don't have anything. And I don't know what's wrong with it ,I want to ask some advice.
Thanks so much of you to solve my so many problems, you really help me so much!

**Comment by sturkmen72** [comment]
could you try with an image like 
`D:\build\C4-Real-time-pedestrian-detection\Release>TestC4Detector D:/test/person.jpg`

**Comment by ziyanwang** [comment]
I try as you write but the result window don't show any thing and only be gray. It is also strange that the window close very fast. I'm so confused.
Thanks to much!

**Comment by sturkmen72** [comment]
if it is possible maybe i can try to help using teamviewer

**Comment by ziyanwang** [comment]
Thank you so much, I solve this problem and I'm so thankful that you really help me so much in the before days ,you are a very good person. I find that my problem is that I use the debug , today I change to release,  and I succeed.
Thanks to much for these days, I am a college student and do this for interests,  you really help me so much!

**Comment by ziyanwang** [comment]
Thank you so much!

**Comment by sturkmen72** [comment]
you are welcome
